const char* usage =
"Usage: serial [OPTION]...[FILE]...\n"
"\n"
"OPTIONS:\n"
"\n"
"  --version     version info\n"
"  --help        this message\n"
"  --log         log config\n"
"\n"
"Examples:\n"
"  serial: will list the serial ports\n"
"  serial \"COM3\": open COM3 console\n"
"\n"
"Source located at https://github.com/jinfeng-zhuang/zstack\n"
"Copyright @ 2021, Jinfeng Zhuang\n";